{
 "title": "Мониторинг ML-модели",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Мониторинг производительности ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum/http_request_duration_seconds_count\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Число запросов к сервису ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Мониторинг логики модели ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  },
  {
   "title": "Среднее и медианное предсказание ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(main_app_predictions_bucket[1m]))\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(main_app_predictions_sum[5m]) / rate(main_app_predictions_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество негативно предсказанных цен ",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 22 },
   "targets": [
    {
     "expr": "increase(neg_price_counter_total[5m]) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}