services:
  main-app:  
    #используем файл с переменными среды
    env_file:
      - ./.env
    # собираем образ с помощью Dockerfile
    build:
      dockerfile: Dockerfile_ml_service
    # перенаправялем порты
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - type: bind
        source: ./models 
        target: /services/models
    hostname: main_app


  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    hostname: prometheus

  grafana:
        image: grafana/grafana
        env_file:
        - ./.env
        ports:
        - "${GRAFANA_PORT}:${GRAFANA_PORT}"
        environment:
        - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
        - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}