FROM python:3.11-slim
# возьмем образ, который мы скачали ранее и в котором уже установлен python

LABEL author=${AUTHOR}
# добавим label, используя переменную среды

COPY . ./services
# копируем файлы в Docker
# название директории внутри контейнера: services

WORKDIR services 
# изменяем рабочую директорию Docker 

RUN pip3 install -r requirements.txt
# инструкция для установки библиотек

EXPOSE ${APP_PORT}
# инструкции для открытия порта, указанного в переменной среды


VOLUME /models
# том с моделями

CMD uvicorn ml_service.main_dummy:app --reload --port ${APP_PORT} --host 0.0.0.0
# измените команду запуска, учитывая порт из .env